server:
  port: 9092

spring:
  datasource:
    password: Abhi@123
    url: jdbc:mysql://localhost:3306/sample2
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

